version: '3.8'

services:
  postgres:
    container_name: portfolio-pg
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: portfolio
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
